### ISSUE TITLE
Rust-gpu 0.6 was just released

### ISSUE THREAD

**Issue by oisyn** [Bevy-Rust-GPU/bevy-rust-gpu#15]
Hi!
Awesome work with this rust-gpu integration for Bevy!

We from rust-gpu just released `0.6.0`. I still have to write the release notes, but I was wondering if I could use this bevy rust-gpu gif as a featured title image?

![image](https://raw.githubusercontent.com/Bevy-Rust-GPU/bevy-rust-gpu/static-assets/hot-rebuild-workflow.gif)

**Comment by Shfty** [comment]
Thanks! Looking forward to the release notes; I'll have a poke around and bring bevy-rust-gpu up to date with it soon.

And absolutely, feel free to use the gif :slightly_smiling_face:

All being well, I should have some more eye candy to show on that front too, once the new [`rust-gpu-sdf`](https://github.com/bevy-rust-gpu/rust-gpu-sdf) crate has stabilized enough to build into an example.

**Comment by oisyn** [comment]
Thanks, it's here: https://github.com/EmbarkStudios/rust-gpu/releases/tag/v0.6.0 🙂

**Comment by Shfty** [comment]
Bevy Rust-GPU is now 0.6 compatible :partying_face:
